pandas는 Python에서 데이터를 쉽고 효율적으로 분석하고 처리하기 위해 사용하는 대표적인 데이터 분석 라이브러리입니다. 엑셀과 비슷한 형태의 표(Tabular Data)를 다룰 수 있으며, Series와 DataFrame이라는 강력한 자료구조를 제공합니다. CSV, Excel, SQL 등의 다양한 데이터 파일을 불러와 정렬, 필터링, 그룹화, 결측치 처리, 통계 분석 등을 간편하게 수행할 수 있으며, 대량의 데이터를 빠르게 가공할 수 있습니다.
```
# 설치
pip install pandas
# 또는
python -m pip install pandas
```

```
import pandas as pd
```

```
pd.__version__
```

In [10]:
import pandas as pd

## 1. Series
Series는 Pandas에서 사용하는 가장 기본적인 1차원 데이터 구조로, 값(Value)과 인덱스(Index)가 함께 구성된 자료형입니다. NumPy의 1차원 배열과 비슷하지만, 각 데이터에 이름표 역할을 하는 인덱스가 추가되어 데이터를 더 체계적으로 관리할 수 있습니다.

![시리즈](./images/시리즈.png)

In [11]:
idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
data = [67, 75, 90, 62, 98]

# pd.Series(데이터, 인덱스, ...)
pd.Series(data)

0    67
1    75
2    90
3    62
4    98
dtype: int64

In [3]:
ser1 = pd.Series(data, idx)
print(ser1)
print(ser1.index)
print(ser1.values)
print(type(ser1.values))

김사과    67
반하나    75
오렌지    90
이메론    62
배애리    98
dtype: int64
Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
[67 75 90 62 98]
<class 'numpy.ndarray'>

### Index 객체란
Index 객체는 Series와 DataFrame에서 각 데이터의 위치를 식별하고 관리하기 위한 “이름표(Label)” 역할을 하는 자료구조입니다. 일반 리스트처럼 보이지만 단순한 데이터 저장용이 아니라, 데이터를 빠르게 검색하고 정렬하며 서로 다른 데이터끼리 매칭할 수 있도록 최적화된 Pandas 전용 객체입니다.

![인덱스객체](./images/인덱스객체.png)

## 2. DataFrame
데이터프레임(DataFrame)은 판다스(Pandas) 라이브러리에서 제공하는 중요하고 강력한 데이터 구조로, 2차원의 테이블 형태 데이터를 다루는 데 사용됩니다. 또한 각 요소는 인덱스(index), 열(column), 값(value)으로 구성되어 있습니다. 데이터프레임은 행과 열로 이루어져 있으며, 각 열은 다양한 데이터 타입을 가질 수 있습니다. 값은 넘파이의 ndarray 기반으로 저장됩니다.

![데이터프레임](./images/데이터프레임.png)

In [4]:
data = [[67, 93, 91],
        [75, 68, 96],
        [87, 81, 82],
        [62, 70, 75],
        [98, 56, 87]]

idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
col = ['국어', '영어', '수학']

# pd.DataFrame(데이터, 인덱스, 컬럼, ...)
pd.DataFrame(data)

    0   1   2
0  67  93  91
1  75  68  96
2  87  81  82
3  62  70  75
4  98  56  87

In [5]:
pd.DataFrame(data, idx)

      0   1   2
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [9]:
pd.DataFrame(data, idx, col)

NameError: name 'pd' is not defined

In [7]:
df = pd.DataFrame(index=idx, columns=col, data=data)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [8]:
print(df.index)
print(df.columns)
print(df.values)

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
Index(['국어', '영어', '수학'], dtype='str')
[[67 93 91]
 [75 68 96]
 [87 81 82]
 [62 70 75]
 [98 56 87]]

In [9]:
# 딕셔너리를 사용하여 데이터프레임을 생성하기
dic = {
    '국어':[67, 75, 76, 62, 98],
    '영어':[93, 68, 81, 70, 56],
    '수학':[91, 96, 82, 75, 87]
}

df = pd.DataFrame(data=dic, index=idx)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  76  81  82
이메론  62  70  75
배애리  98  56  87

## 3. CSV 파일 읽어오기
CSV 파일은 Comma-Separated Values(쉼표로 구분된 값) 파일의 약자로, 데이터를 단순한 텍스트 형식으로 저장하는 데 사용되는 파일 형식입니다.

In [8]:
df = pd.read_csv('./광고모델_브랜드평판.csv')
df

NameError: name 'pd' is not defined

In [11]:
type(df)

pandas.DataFrame

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     str
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: str(7)
memory usage: 1.2 KB

In [13]:
df.columns

Index(['이름', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='str')

In [14]:
new_columns = ['name', 'company', 'gender', 'birthday', 'height', 'blood', 'brand']
df.columns = new_columns
df

   name      company gender    birthday   height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271

In [15]:
# describe(): 통계 정보를 반환
df.describe(include=str)

       name  company gender    birthday height blood      brand
count    20       20     20          20     20    18         20
unique   20       19      2          20     15     4         20
top     변우석  아티스트컴퍼니      남  1991-10-31  178cm     B  3,762,141
freq      1        2     15           1      3     7          1

![통계정보](./images/통계정보.png)

In [16]:
# 원하는 개수의 데이터 보기
df.head() # 상위 5개의 row를 출력

  name    company gender    birthday   height blood      brand
0  변우석   바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1  임영웅      물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2  손흥민  로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
3  박지훈   YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
4  유재석        안테나      남  1972-08-14    178cm     B  2,015,312

In [17]:
df.head(3) # 상위 3개의 row를 출력

  name    company gender    birthday   height blood      brand
0  변우석   바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1  임영웅      물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2  손흥민  로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512

In [18]:
df.tail() # 하위 5개의 row를 출력

   name    company gender    birthday height blood    brand
15  박보검     더블랙레이블      남  1993-06-16  182cm     O  451,540
16  엄태구        팀호프      남  1983-11-09  181cm     O  380,064
17  구교환      나무엑터스      남  1982-12-14  182cm     A  371,673
18  지예은  S&A엔터테인먼트      여  1994-07-26  171cm   NaN  370,543
19  전지현     이음해시태그      여  1981-10-30  173cm     B  358,271

In [19]:
df.tail(2) # 하위 2개의 row를 출력

   name    company gender    birthday height blood    brand
18  지예은  S&A엔터테인먼트      여  1994-07-26  171cm   NaN  370,543
19  전지현     이음해시태그      여  1981-10-30  173cm     B  358,271

## 4. 정렬하기

In [20]:
df.sort_index() # index로 오름차순 정렬: 기본값

   name      company gender    birthday   height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271

In [21]:
df.sort_index(ascending=False) # index로 내림차순 정렬

   name      company gender    birthday   height blood      brand
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141

In [22]:
df.sort_values(by='height') # 키로 오름차순 정렬

   name      company gender    birthday   height blood      brand
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141

In [23]:
df.sort_values(by='height', ascending=False) # 키로 내림차순 정렬

   name      company gender    birthday   height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169

> 👉  문자열 비교는 사전(Dictionary) 순서처럼 비교하기 때문에 "182cm" > "182.2cm" 처럼 이상한 결과가 나올 수 있습니다.

In [24]:
df['height'] = df['height'].str.replace('cm', '').astype(float)
df

   name      company gender    birthday  height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3,762,141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3,349,309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3,067,512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2,831,201
4   유재석          안테나      남  1972-08-14   178.0     B  2,015,312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1,085,281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1,015,456
7   고윤정          MAA      여  1996-04-22   163.0     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10   160.0     B    831,169
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B    664,985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O    651,035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A    561,519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A    543,485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B    486,700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN    481,761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O    451,540
16  엄태구          팀호프      남  1983-11-09   181.0     O    380,064
17  구교환        나무엑터스      남  1982-12-14   182.0     A    371,673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30   173.0     B    358,271

> 👉   cm 문자열을 제거한 뒤 숫자(float)로 변환

In [7]:
df['brand'] = df['brand'].str.replace(',', '').astype(int)
df

NameError: name 'df' is not defined

> 👉    brand 컬럼도 현재 숫자가 아니라 문자열(String) 상태. 쉼표(,)를 제거한 뒤 숫자로 변환

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     str
 1   company   20 non-null     str
 2   gender    20 non-null     str
 3   birthday  20 non-null     str
 4   height    20 non-null     float64
 5   blood     18 non-null     str
 6   brand     20 non-null     int64
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [27]:
df.describe()

           height         brand
count   20.000000  2.000000e+01
mean   177.325000  1.206734e+06
std      7.906751  1.125405e+06
min    160.000000  3.582710e+05
25%    173.000000  4.742058e+05
50%    179.000000  6.580100e+05
75%    182.400000  1.317789e+06
max    190.300000  3.762141e+06

In [28]:
# 1차 정렬: 키(내림차순), 2차 정렬: 브랜드(내림차순)
df.sort_values(by=['height', 'brand'], ascending=[False, False], na_position='first')

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
19  전지현       이음해시태그      여  1981-10-30   173.0     B   358271
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10   160.0     B   831169

![describe](./images/describe.png)

## 5. 인덱싱

In [3]:
df.head()

NameError: name 'df' is not defined

In [4]:
df['blood']

NameError: name 'df' is not defined

In [ ]:
type(df['blood'])

In [ ]:
df.head(3)

In [5]:
# loc 인덱싱
df.loc[:, 'name']

NameError: name 'df' is not defined

> 👉 loc는 DataFrame이나 Series에서 인덱스 이름(Label)과 컬럼명을 기준으로 데이터를 선택하는 인덱서(Indexer)입니다. 즉, 숫자 위치가 아니라 실제 행 이름과 열 이름을 사용하여 데이터를 가져옵니다. loc는 사람이 읽기 쉽고 데이터 의미를 기준으로 접근하기 때문에 데이터 분석과 전처리 작업에서 가장 많이 사용하는 방식 중 하나입니다.

In [ ]:
df.loc[2:5, 'name'] # 5번을 포함

In [ ]:
df.loc[2:5, ['name', 'gender', 'height']]

In [ ]:
df.loc[[2,5], ['name', 'gender', 'height']]

In [ ]:
df.loc[2:5, 'name':'gender']

In [ ]:
# iloc 인덱싱: index로 인덱싱
df.iloc[:, 0]

> 👉 iloc는 DataFrame이나 Series에서 숫자 위치(Index Position)를 기준으로 데이터를 선택하는 인덱서(Indexer)입니다. 즉, 실제 인덱스 이름이 아니라 행과 열의 순서 번호를 사용하여 데이터를 가져옵니다. iloc는 데이터의 실제 이름과 상관없이 순서 기준으로 접근하기 때문에 반복 처리나 특정 위치 데이터를 다룰 때 많이 사용됩니다.

In [ ]:
df.iloc[:, 0:3] # 3을 포함하지 않음

In [ ]:
df.iloc[:, [0, 3]]

In [ ]:
df.iloc[1:5, 0:2]

In [ ]:
df['height'] >= 180

In [ ]:
df[df['height'] >= 180]

In [ ]:
df[df['height'] >= 180]['name'] # df['name'][df['height'] >= 180]

In [ ]:
df[df['height'] >= 180][['name', 'gender', 'height']]

In [ ]:
df.loc[df['height'] >= 180, ['name', 'gender', 'height']]

In [ ]:
blood = ['A', 'B']
df['blood'].isin(blood)

In [ ]:
df[df['blood'].isin(blood)] # df.loc[df['blood'].isin(blood),:]

## 6. 결측값
결측값(Missing Value)은 데이터가 존재하지 않거나 비어있는 값을 의미하며, 보통 NaN(Not a Number) 형태로 표현됩니다. 예를 들어 키, 몸무게, 나이 같은 정보가 입력되지 않았거나 수집 과정에서 누락된 경우 결측값이 발생합니다. 데이터 분석과 머신러닝에서는 결측값이 매우 중요하며, 그대로 두면 평균 계산, 통계 분석, 모델 학습 과정에서 오류나 성능 저하가 발생할 수 있습니다. 결측값 처리는 데이터 품질을 높이고 정확한 분석 결과를 얻기 위한 매우 중요한 데이터 전처리 과정입니다.

In [12]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.isna()
# 또는
df.isnull()

In [ ]:
df.notna()
# 또는
df.notnull()

In [ ]:
df['height'].isna()

In [ ]:
df[df['height'].isna()]

In [13]:
import numpy as np

# df.loc[8, 'height'] = np.nan
# df.loc[19, 'height'] = np.nan

df.loc[[8, 19], 'height'] = np.nan

NameError: name 'df' is not defined

In [ ]:
df[df['height'].isna()]

In [ ]:
df[df['height'].isna()]['name']

In [ ]:
df[df['height'].notnull()]

In [ ]:
df[~df['height'].isnull()]

In [ ]:
df.loc[df['height'].notnull(), ['name', 'company', 'gender']]

In [ ]:
df_copy = df.copy()
df_copy

In [ ]:
df_copy['height']

In [ ]:
# fillna(): 결측값을 채워주는 함수
df_copy['height'].fillna(0) # df_copy['height].fillna(0, inplace=True) 적용

In [ ]:
df_copy['height']

In [ ]:
height = df_copy['height'].mean()
height

In [ ]:
df_copy['height'] = df_copy['height'].fillna(height)
df_copy['height']

In [ ]:
df_copy = df.copy()
df_copy['height']

In [ ]:
height = df_copy['height'].median() # 50%값, 중위
height

In [ ]:
df_copy['height'].fillna(height, inplace=True)
df_copy['height']

In [ ]:
df_copy = df.copy()
df_copy

In [ ]:
# dropna(): 결측값이 있는 행 또는 열을 제거. 결측값이 한개라도 있는 경우 삭제
# axis=0 (행 삭제)
df_copy.dropna()

In [ ]:
df_copy.dropna(axis=1) # 결측값이 있는 열을 제거